import { digitornFetch, digitornConfig } from "./src/cli/cmd/tui/context/digitorn"
const cfg = digitornConfig()
const f = digitornFetch(cfg)
const list: any = await (await f(`${cfg.url}/digitorn/apps` as any)).json()
console.log("apps:", list.length)
for (const a of list.slice(0, 12)) console.log(`  ${a.current ? "*" : " "} ${a.id.padEnd(18)} ${a.category.padEnd(8)} ${a.name}`)
const sw: any = await (await f(`${cfg.url}/digitorn/app` as any, { method: "POST", body: JSON.stringify({ app_id: "chat-deepseek" }) })).json()
console.log("switched →", sw.app)
const list2: any = await (await f(`${cfg.url}/digitorn/apps` as any)).json()
console.log("current now:", list2.find((a: any) => a.current)?.id)
const sess: any = await (await f(`${cfg.url}/session` as any)).json()
console.log("sessions for chat-deepseek:", Array.isArray(sess) ? sess.length : "?")
process.exit(0)
